### PR TITLE
Add chapter 4 content

### PR DESCRIPTION
**Pull request by ClaireHoffmann**
Addresses #7.

### CODE REVIEW

**Comment by ClaireHoffmann** [comment]
Hello! 

Sorry, I wanted to convert this pull request to draft, but it doesn't seem to work (I am more used to GitLab 😅)

**Comment by ClaireHoffmann** [comment]
I haven't changed much compared to the software carpentry version for now, I only added a few 'call out' boxes.

Also, I am wondering whether we should keep the Dracula and planets story? I see that for chapter 3, we dropped it, whereas chapter 5 still has it.

**Comment by kateburnettisaacs** [comment]
I agree that we should make the project names a little more generic. I'm wondering if we should make the project refer to the inflammation data/work found in the R and Python courses. What do you think?

**Comment by kateburnettisaacs** [comment]
Hi @ClaireHoffmann can you ask me to review this pull request so I can accept it?

**Review by thoughthollow — APPROVED** [review]

**Pull request merged**
